language: ruby
rvm:
  - 2.3
  - 2.4
services:
  - mysql
  - postgresql
addons:
  postgresql: "9.5"
env:
  - DATABASE=mysql
  - DATABASE=postgresql
gemfile:
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
before_script:
  - cd spec/dummy
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake db:seed RAILS_ENV=test
  - cd ../..
script: bundle exec rspec
