language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
services:
  - mysql
  - postgresql
addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.4
env:
  - DATABASE=mysql
  - DATABASE=postgresql
  - DATABASE=postgis
gemfile:
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails60.gemfile
  - gemfiles/rails61.gemfile
matrix:
  exclude:
  - rvm: 2.3
    gemfile: gemfiles/rails60.gemfile
  - rvm: 2.3
    gemfile: gemfiles/rails61.gemfile
  - rvm: 2.4
    gemfile: gemfiles/rails60.gemfile
  - rvm: 2.4
    gemfile: gemfiles/rails61.gemfile
  - rvm: 3.0
    gemfile: gemfiles/rails50.gemfile
  - rvm: 3.0
    gemfile: gemfiles/rails51.gemfile
  - rvm: 3.0
    gemfile: gemfiles/rails52.gemfile
before_script:
  - psql -U postgres -c "create extension postgis"
  - cd spec/dummy
  - bundle exec rake db:create db:migrate db:seed RAILS_ENV=test
  - cd ../..
script:
  - bundle exec rspec
